repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        name: Ensure correct trailing whitespace
    -   id: end-of-file-fixer
        name: Fix EOF
    -   id: check-yaml
        name: Check YAML formatting

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
    -   id: ruff
        name: Enforce Ruff rules
    -   id: ruff-format
        name: Auto-formatting Python code
